### ISSUE TITLE
Split graph output into JSON + actual graph

### ISSUE THREAD

**Issue by dimaqq** [dimaqq/awaitwhat#2]
Currently the task dependency graph is generated in one go.

It would be awesome to split this in 2 stages:
1. generate plain data (nodes, edges, text)
2. convert plain data into a dot graph

When that's done, it becomes possible to:
* write tests over 1. :)
* output 1. as JSON
* output 1. as plain text, like Python traceback

guts: https://github.com/dimaqq/awaitwhat/blob/3b86e6351366a24e69c23c0b149559de8e90f0d2/awaitwhat/dot.py#L59-L65

**Comment by africanbeat** [comment]
May I start working on this issue?

**Comment by dimaqq** [comment]
Yes, of course!

**Comment by freedomofkeima** [comment]
#17

**Comment by dimaqq** [comment]
Fixed in #17
