### ISSUE TITLE
awaitwhat weird output on sleep loop

### ISSUE THREAD

**Issue by yoava333** [dimaqq/awaitwhat#22]
I'm using python 3.7.6 (AMD64) on MacOS, I used version (https://github.com/dimaqq/awaitwhat/commit/baa4c73931a61965767e72a8581e7f493a076b34) 

I took the `examples/test_signal.py` changed it to a while loop, and changed the signal, see below:
```
--- a/examples/test_signal.py
+++ b/examples/test_signal.py
@@ -12,10 +12,10 @@ async def job():


 async def foo():
-    signal.alarm(1)
-    await asyncio.sleep(1)
+    while True:
+        await asyncio.sleep(1)


 if __name__ == "__main__":
-    awaitwhat.helpers.register_signal(signal.SIGALRM)
+    awaitwhat.helpers.register_signal(signal.SIGINFO)
     asyncio.run(main())
```

When I'm sending SIGINFO to the process, the output is the following image:
![image](https://user-images.githubusercontent.com/1495026/72728549-4fe8a000-3b96-11ea-8f60-3c742caa44df.png)

Is this intended? How should I interpret this image?

**Comment by dimaqq** [comment]
Clearly something got messed up.
Looks like an info string got decomposed into a bunch of of nodes, e.g. `await async.. → 3x 'a', 1x 'w', ...`
I suspect it's a regression in this month's commits 😅

This kinda hits the conceptual problem on the head:
* a task graph may end in a leaf, e.g. `asyncio.sleep()`
* while another may point to other tasks, e.g. `asyncio.gather()` → `Task-4`, `Task-9`

I'm not sure how to best represent this duality in code...
Do you have any good ideas?

**Comment by yoava333** [comment]
I found the issue, https://github.com/dimaqq/awaitwhat/blob/master/awaitwhat/blocker.py#L14 returns a string and not a list of one string. After fixing this issue the output looks like this 
![image](https://user-images.githubusercontent.com/1495026/72783757-dbfad600-3c2f-11ea-89f2-e08fef208da2.png)

I think the representation is good, let's see how it scales to bigger asyncio state

**Comment by dimaqq** [comment]
Ah, yes, you got it!
